on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v1
        with:
          repository: cosmos-sdk-epub
          tags: latest
      - uses: shrink/actions-docker-extract@v1
        with:
          image: cosmos-sdk-epub
          path: /tmp/cosmos-sdk/docs/book.epub
      - name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: dist
